// DrumVariationEngine.swift — generation step 13
//
// Adds human-sounding drum transitions — fills and cymbal variations — on top of the
// repeating Motorik base patterns generated by DrumGenerator.
//
// Two triggers for fills:
//   1. Section transitions (A→B, B→A, body→outro): drummer cues the section change.
//   2. Instrument entrances: a non-drum track comes in after ≥2 silent bars.
//
// Fill lengths (weighted 60 / 30 / 10):
//
//   1-BEAT fills — last 4 steps (steps 12-15). Six variations ranging from barely audible
//   to moderately energetic. The Motorik/Krautrock aesthetic prizes subtlety; the drummer
//   is a metronome who cues transitions with the minimum necessary gesture.
//
//     v0  Ghost Whisper     — ghost snare step 13 + accent step 15. No hat stripping.
//                             Inspired by Jaki Liebezeit (CAN) — almost imperceptible,
//                             just a flicker of texture going into the downbeat.
//     v1  Sidestick Flam    — sidestick step 14 + snare step 15. No hat stripping.
//                             Classic Motorik cue; the sidestick "rim" click signals
//                             the change without breaking groove.
//     v2  Hat Triplet Cue   — extra closed hat step 13 + ghost snare 14 + snare 15.
//                             No hat stripping. Creates a subtle triplet-feel push into
//                             beat 1 while keeping the groove intact.
//     v3  Double Snap       — strip hats 14-15, snare 14 + snare 15.
//                             Simple two-note punch. Stewart Copeland (Police) uses
//                             this kind of minimal cue constantly.
//     v4  Floor Tap         — strip hats 13-15, hiFloorTom 13 + snare 15.
//                             One tom tap before the final snare. Very common in
//                             minimal electronic and post-punk drumming.
//     v5  Short Roll        — strip hats 12-15, four snares ascending velocity.
//                             The standard "rock fill in 1 beat." Energetic but contained.
//
//   2-BEAT fills — last 8 steps (steps 8-15). Four variations; all strip hats 8-15.
//
//     v0  Snare→Toms→Snare  — snare pair, tom pair, snare flourish.
//                             Versatile standard fill; works in most rock contexts.
//     v1  Bonham Descent     — hi-tom → hi-mid → low-mid → floor tom → snares.
//                             Inspired by John Bonham's iconic "Moby Dick" tom runs.
//     v2  Double-Time Roll   — 16 snares as a ghost roll (16th-note feel).
//                             Inspired by Stewart Copeland's dense snare patterning
//                             and the Clocks/Police snare texture approach.
//     v3  Funk Cross-Pattern — kick + snare alternation with floor toms.
//                             Inspired by Bernard Purdie and Clyde Stubblefield —
//                             the "Amen break" ancestor, kick-snare cross-feel.
//
//   3-BEAT fills — last 12 steps (steps 4-15). Three variations; all strip hats 4-15.
//
//     v0  Tom Descend        — hi→mid→floor tom cascade into snare flourish.
//     v1  Crescendo Roll     — 12-step snare ghost roll building from ppp to fff.
//                             Inspired by Bill Bruford (King Crimson) and jazz
//                             orchestral crescendo builds.
//     v2  Alternating Toms   — hi-mid ↔ floor tom alternation then snare close.
//                             Inspired by prog rock tom interplay (Neil Peart,
//                             Phil Collins "In the Air Tonight" outro style).
//
// For subtle 1-beat fills (v0, v1, v2): no crash added (too dramatic for a whisper cue).
// For all others: crash lands on beat 1 of the following bar.
//
// Cymbal variations (after 16+ identical body bars):
//   Every 8 bars of an unbroken identical run, one bar is varied:
//     var-0: ride swap — closed hats replaced by ride cymbals for one bar.
//     var-1: open hat accent on "and of 4" (step 14).
//     var-2: crash on beat 1 + open hat colour on "and of 2" (step 6).
//
// Anchors never touched: kick on beats 1+3 (steps 0, 8) and snare on beats 2+4
// (steps 4, 12) are preserved unless the fill naturally absorbs them.
//
// Bass locking (applied alongside fills):
//   For 2-beat fills (steps 8-15): bass events are cleared from the fill region;
//   a single root-anchor note is added at step 8 (beat 3) to lock with the fill entry.
//   For 3-beat fills (steps 4-15): bass events are cleared from steps 4-15 entirely
//   (complete drop into the fill — the single bass note on beat 1 provides the anchor).
//   1-beat fills are too subtle to warrant bass modification.

struct DrumVariationEngine {

    // MARK: - Fill bar info (shared between full generation and bass-regen path)

    private struct FillBarInfo {
        let bar: Int
        let fillLength: Int   // 0 = 1-beat, 1 = 2-beat, 2 = 3-beat
    }

    // MARK: - Public: full apply (drums + bass)

    static func apply(
        trackEvents: [[MIDIEvent]],
        frame: GlobalMusicalFrame,
        structure: SongStructure,
        seed: UInt64,
        chillMode: Bool = false
    ) -> [[MIDIEvent]] {
        var rng = SeededRNG(seed: seed &+ 0xDEAD_BABE_F11E_D20B)
        var drumEvents = trackEvents[kTrackDrums]
        var result = trackEvents

        // MARK: Step 1 — Identify fill bars

        let fillBars = computeFillBars(trackEvents: trackEvents, frame: frame, structure: structure, chillMode: chillMode)

        // MARK: Step 2 — Apply fills to drums, collecting fill type info

        var fillInfos: [FillBarInfo] = []

        for fillBar in fillBars.sorted() {
            guard let sec = structure.section(atBar: fillBar),
                  sec.label != .intro && sec.label != .outro else { continue }
            // Chill: no 3-beat fills (tom cascades are rock-style, inappropriate for jazz chill)
            // Chill weights: 80% 1-beat, 20% 2-beat, 0% 3-beat
            let fillLength = chillMode
                ? rng.weightedPick([0.80, 0.20, 0.00])
                : rng.weightedPick([0.70, 0.25, 0.05])
            drumEvents = applyFill(to: drumEvents, bar: fillBar, fillLength: fillLength,
                                   frame: frame, structure: structure, chillMode: chillMode, rng: &rng)
            fillInfos.append(FillBarInfo(bar: fillBar, fillLength: fillLength))
        }

        // MARK: Step 3 — Cymbal variations on long identical runs

        drumEvents = applyRunVariations(to: drumEvents, frame: frame,
                                        structure: structure, fillBars: fillBars, rng: &rng)

        result[kTrackDrums] = drumEvents

        // MARK: Step 4 — Lock bass to multi-beat fills
        // Use a separate RNG so bass decisions don't depend on cymbal-variation draw order.

        var bassLockRNG = SeededRNG(seed: seed &+ 0xB455_F177_D20B_1337)
        result[kTrackBass] = applyBassLocking(bassEvents: trackEvents[kTrackBass],
                                              fillInfos: fillInfos,
                                              rng: &bassLockRNG)

        return result
    }

    // MARK: - Public: bass-only locking for use during bass track regeneration
    //
    // Replays the same fill detection + rng sequence as the original apply() call
    // (using the original globalSeed), then applies only the bass locking step.
    // The drum track in trackEvents must already contain the fills from the
    // original generation; only trackEvents[kTrackBass] is modified.

    static func lockBassToExistingFills(
        trackEvents: [[MIDIEvent]],
        frame: GlobalMusicalFrame,
        structure: SongStructure,
        seed: UInt64
    ) -> [[MIDIEvent]] {
        var rng = SeededRNG(seed: seed &+ 0xDEAD_BABE_F11E_D20B)

        let fillBars = computeFillBars(trackEvents: trackEvents, frame: frame, structure: structure, chillMode: false)

        var fillInfos: [FillBarInfo] = []
        for fillBar in fillBars.sorted() {
            guard let sec = structure.section(atBar: fillBar),
                  sec.label != .intro && sec.label != .outro else { continue }
            let fillLength = rng.weightedPick([0.70, 0.25, 0.05])
            // Consume the variation rng draw to stay in step with the original sequence
            switch fillLength {
            case 0:  _ = rng.nextInt(upperBound: 6)
            case 2:  _ = rng.nextInt(upperBound: 3)
            default: _ = rng.nextInt(upperBound: 4)
            }
            fillInfos.append(FillBarInfo(bar: fillBar, fillLength: fillLength))
        }

        var bassLockRNG = SeededRNG(seed: seed &+ 0xB455_F177_D20B_1337)
        var result = trackEvents
        result[kTrackBass] = applyBassLocking(bassEvents: trackEvents[kTrackBass],
                                              fillInfos: fillInfos,
                                              rng: &bassLockRNG)
        return result
    }

    // MARK: - Fill bar detection (shared)

    private static func computeFillBars(
        trackEvents: [[MIDIEvent]],
        frame: GlobalMusicalFrame,
        structure: SongStructure,
        chillMode: Bool = false
    ) -> Set<Int> {
        var fillBars = Set<Int>()

        // Section transition fills: bar before each new body section.
        var prevSectionLabel: SectionLabel? = nil
        for bar in 0..<frame.totalBars {
            guard let sec = structure.section(atBar: bar) else { continue }
            if sec.label != prevSectionLabel {
                if bar > 0, sec.label != .intro && sec.label != .outro {
                    let fillBar = bar - 1
                    if let prevSec = structure.section(atBar: fillBar),
                       prevSec.label != .intro {
                        fillBars.insert(fillBar)
                    }
                }
            }
            prevSectionLabel = sec.label
        }

        // Instrument entrance fills: non-drum track comes in after ≥2 silent bars.
        // Skipped in chillMode — jazz/chill doesn't drum-fanfare every instrument entry.
        if !chillMode {
            for trackIdx in 0..<kTrackDrums {
                let tEvents = trackEvents[trackIdx]
                let presence: [Bool] = (0..<frame.totalBars).map { bar in
                    let bs = bar * 16
                    return tEvents.contains { $0.stepIndex >= bs && $0.stepIndex < bs + 16 }
                }
                for bar in 2..<frame.totalBars {
                    guard presence[bar] && !presence[bar - 1] && !presence[bar - 2] else { continue }
                    let fillBar = bar - 1
                    guard let sec = structure.section(atBar: fillBar),
                          sec.label != .intro && sec.label != .outro else { continue }
                    fillBars.insert(fillBar)
                }
            }
        }

        // Periodic body fills: fire on bars 7, 15, 23 … within each body section.
        // Suppressed in chillMode — fills only at structural boundaries (section transitions above).
        if !chillMode {
            for bar in 0..<frame.totalBars {
                guard let sec = structure.section(atBar: bar),
                      sec.label != .intro && sec.label != .outro else { continue }
                let barInSection = bar - sec.startBar
                guard (barInSection + 1) % 8 == 0 else { continue }
                guard !fillBars.contains(bar) else { continue }
                fillBars.insert(bar)
            }
        }

        // Chill: enforce a 16-bar minimum gap between any two fills to prevent fill clustering.
        if chillMode && fillBars.count > 1 {
            var spaced = Set<Int>()
            var lastFill = -16
            for bar in fillBars.sorted() {
                if bar - lastFill >= 16 {
                    spaced.insert(bar)
                    lastFill = bar
                }
            }
            return spaced
        }

        return fillBars
    }

    // MARK: - Bass locking

    // For 2-beat fills: clear bass from steps 8-15, add one root-anchor at step 8.
    //   The bass plays beats 1-2 normally, then lands a single accent on beat 3 right
    //   as the fill begins — creating a rhythmic "lock-in" without competing with toms/snares.
    //
    // For 3-beat fills: clear bass from steps 4-15. 2/3 of the time this is a complete
    //   drop (beat 1 alone provides harmonic grounding). 1/3 of the time the bass plays
    //   one of two supportive responses:
    //     - Root drone: a single sustained note held across the full fill region (soft,
    //       sits under the drums without competing).
    //     - Matching accents: two quarter-note root hits at beats 2 and 3, marking the
    //       same downbeats the drummer is accenting.
    //
    // 1-beat fills: no bass change (too subtle to disrupt the bass line).

    private static func applyBassLocking(
        bassEvents: [MIDIEvent],
        fillInfos: [FillBarInfo],
        rng: inout SeededRNG
    ) -> [MIDIEvent] {
        var result = bassEvents

        for info in fillInfos {
            guard info.fillLength > 0 else { continue }  // skip 1-beat fills

            let barStart = info.bar * 16
            // fillLength 1 (2-beat) → fill region starts at step 8 (beat 3)
            // fillLength 2 (3-beat) → fill region starts at step 4 (beat 2)
            let fillRegionStart = (info.fillLength == 2) ? barStart + 4 : barStart + 8

            // Find the note to use as anchor: prefer beat 1 of the bar, else first note
            // in the region before the fill starts.
            let preRegion = result.filter {
                $0.stepIndex >= barStart && $0.stepIndex < fillRegionStart
            }
            let anchorNote: UInt8?
            if let beatOneEv = preRegion.first(where: { $0.stepIndex == barStart }) {
                anchorNote = beatOneEv.note
            } else {
                anchorNote = preRegion.min(by: { $0.stepIndex < $1.stepIndex })?.note
            }
            guard let anchor = anchorNote else { continue }

            // Strip bass from the fill region
            result = result.filter { ev in
                !(ev.stepIndex >= fillRegionStart && ev.stepIndex < barStart + 16)
            }

            if info.fillLength == 1 {
                // 2-beat fill: single anchor note at fill entry (beat 3)
                result.append(MIDIEvent(stepIndex: fillRegionStart,
                                        note: anchor, velocity: 72, durationSteps: 2))
            } else {
                // 3-beat fill: 2/3 complete drop, 1/3 supportive response
                let variant = rng.nextInt(upperBound: 3)
                if variant == 0 {
                    // Root drone: sustained through the fill region (12 steps = 3 beats), soft
                    result.append(MIDIEvent(stepIndex: fillRegionStart,
                                            note: anchor, velocity: 58, durationSteps: 12))
                } else if variant == 1 {
                    // Matching accents: quarter-note hits at beat 2 and beat 3
                    result.append(MIDIEvent(stepIndex: barStart + 4,
                                            note: anchor, velocity: 65, durationSteps: 2))
                    result.append(MIDIEvent(stepIndex: barStart + 8,
                                            note: anchor, velocity: 68, durationSteps: 2))
                }
                // variant == 2: complete drop (no notes added)
            }
        }

        return result
    }

    // MARK: - Fill application

    private static func applyFill(
        to events: [MIDIEvent],
        bar: Int, fillLength: Int,
        frame: GlobalMusicalFrame,
        structure: SongStructure,
        chillMode: Bool = false,
        rng: inout SeededRNG
    ) -> [MIDIEvent] {
        let barStart = bar * 16
        let data: FillData

        switch fillLength {
        case 0:  data = oneBeatFill(barStart: barStart, variation: rng.nextInt(upperBound: 6))
        case 2:  data = threeBeatFill(barStart: barStart, variation: rng.nextInt(upperBound: 3))
        default:
            // Chill: restrict to snare-only variants (v2=double-time roll, v3=funk cross-pattern)
            // to avoid rock-style tom fills. Standard: all 4 variants available.
            let v = chillMode ? 2 + rng.nextInt(upperBound: 2) : rng.nextInt(upperBound: 4)
            data = twoBeatFill(barStart: barStart, variation: v)
        }

        // Strip drum notes from the fill region.
        // Subtle 1-beat fills (stripFrom == barStart+16) do no stripping at all.
        // For 1-beat fills that do strip (steps 12-15) and all 2- and 3-beat fills:
        // clear ALL percussion — cymbals, snare, AND kick — so the fill can be heard
        // clearly rather than playing on top of the continuing groove pattern.
        // Beat 1 (step 0) is always before stripFrom and is never removed.
        let notesToStrip: Set<UInt8> = [
            GMDrum.closedHat.rawValue, GMDrum.openHat.rawValue,
            GMDrum.pedalHat.rawValue,  GMDrum.ride.rawValue,
            GMDrum.rideBell.rawValue,
            GMDrum.kick.rawValue,
            GMDrum.snare.rawValue,     GMDrum.snare2.rawValue,
            GMDrum.sidestick.rawValue,
        ]
        var filtered = events.filter { ev in
            guard ev.stepIndex >= data.stripFrom && ev.stepIndex < barStart + 16 else { return true }
            return !notesToStrip.contains(ev.note)
        }

        filtered += data.notes

        // Add crash on beat 1 of next bar (suppressed for whisper fills)
        if data.addCrash {
            let nextBar = bar + 1
            if nextBar < frame.totalBars,
               let nextSec = structure.section(atBar: nextBar),
               nextSec.label != .intro && nextSec.label != .outro {
                let crashStep = nextBar * 16
                if !filtered.contains(where: {
                    $0.stepIndex == crashStep && $0.note == GMDrum.crash1.rawValue
                }) {
                    filtered.append(MIDIEvent(stepIndex: crashStep,
                                              note: GMDrum.crash1.rawValue,
                                              velocity: data.crashVelocity, durationSteps: 1))
                }
            }
        }

        return filtered
    }

    // MARK: - Fill data container

    private struct FillData {
        let stripFrom: Int          // absolute step; events at [stripFrom, barStart+16) are cleared
        let notes: [MIDIEvent]      // fill notes (absolute step indices)
        let addCrash: Bool
        let crashVelocity: UInt8
    }

    // MARK: - 1-beat fill catalog (steps 12-15)

    private static func oneBeatFill(barStart: Int, variation: Int) -> FillData {
        switch variation {

        case 0:  // Ghost Whisper — Jaki Liebezeit / CAN style. Barely audible.
            return FillData(
                stripFrom: barStart + 16,   // no hat stripping — hats keep rolling
                notes: [
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.snare.rawValue, velocity: 28, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue, velocity: 82, durationSteps: 1),
                ],
                addCrash: false, crashVelocity: 0)

        case 1:  // Sidestick Flam — classic minimal Motorik cue. No hat disruption.
            return FillData(
                stripFrom: barStart + 16,
                notes: [
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.sidestick.rawValue, velocity: 44, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,     velocity: 90, durationSteps: 1),
                ],
                addCrash: false, crashVelocity: 0)

        case 2:  // Hat Triplet Cue — triplet push into beat 1. Hats unchanged.
            return FillData(
                stripFrom: barStart + 16,
                notes: [
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.closedHat.rawValue, velocity: 42, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue,     velocity: 38, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,     velocity: 92, durationSteps: 1),
                ],
                addCrash: false, crashVelocity: 0)

        case 3:  // Double Snap — two snares on the last two 16ths. Clean and direct.
            return FillData(
                stripFrom: barStart + 14,
                notes: [
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue, velocity: 72, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue, velocity: 100, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 88)

        case 4:  // Floor Tap — one floor tom then snare. Simple, effective.
            return FillData(
                stripFrom: barStart + 13,
                notes: [
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.highFloorTom.rawValue, velocity: 62, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,        velocity: 96, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 90)

        default: // Short Roll — four snares, the standard 1-beat fill.
            return FillData(
                stripFrom: barStart + 12,
                notes: [
                    MIDIEvent(stepIndex: barStart + 12, note: GMDrum.snare.rawValue, velocity: 70, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.snare.rawValue, velocity: 62, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue, velocity: 88, durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue, velocity: 100, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 95)
        }
    }

    // MARK: - 2-beat fill catalog (steps 8-15)

    private static func twoBeatFill(barStart: Int, variation: Int) -> FillData {
        let strip = barStart + 8
        switch variation {

        case 0:  // Snare→Toms→Snare — versatile standard fill.
            return FillData(
                stripFrom: strip,
                notes: [
                    MIDIEvent(stepIndex: barStart +  8, note: GMDrum.snare.rawValue,        velocity: 72,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  9, note: GMDrum.snare.rawValue,        velocity: 62,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 10, note: GMDrum.lowFloorTom.rawValue,  velocity: 80,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 11, note: GMDrum.lowFloorTom.rawValue,  velocity: 75,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 12, note: GMDrum.highFloorTom.rawValue, velocity: 85,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.highFloorTom.rawValue, velocity: 80,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue,        velocity: 92,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,        velocity: 100, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 100)

        case 1:  // Bonham Descent — hi to low tom cascade into snares.
            return FillData(
                stripFrom: strip,
                notes: [
                    MIDIEvent(stepIndex: barStart +  8, note: GMDrum.hiTom.rawValue,       velocity: 80,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  9, note: GMDrum.hiTom.rawValue,       velocity: 72,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 10, note: GMDrum.hiMidTom.rawValue,    velocity: 78,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 11, note: GMDrum.lowMidTom.rawValue,   velocity: 80,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 12, note: GMDrum.lowFloorTom.rawValue, velocity: 85,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.lowFloorTom.rawValue, velocity: 80,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue,       velocity: 95,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,       velocity: 105, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 100)

        case 2:  // Double-Time Roll — 16 snares, ghost/accent alternation. Copeland style.
            return FillData(
                stripFrom: strip,
                notes: (8..<16).map { offset in
                    let vel: UInt8 = (offset % 2 == 0) ? 78 : 48
                    return MIDIEvent(stepIndex: barStart + offset,
                                     note: GMDrum.snare.rawValue,
                                     velocity: vel, durationSteps: 1)
                },
                addCrash: true, crashVelocity: 100)

        default: // Funk Cross-Pattern — kick + snare alternation. Purdie / Stubblefield influence.
            return FillData(
                stripFrom: strip,
                notes: [
                    MIDIEvent(stepIndex: barStart +  8, note: GMDrum.kick.rawValue,         velocity: 92,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  9, note: GMDrum.snare.rawValue,        velocity: 68,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 10, note: GMDrum.kick.rawValue,         velocity: 85,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 11, note: GMDrum.snare.rawValue,        velocity: 62,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 12, note: GMDrum.highFloorTom.rawValue, velocity: 82,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.highFloorTom.rawValue, velocity: 75,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue,        velocity: 90,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,        velocity: 100, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 95)
        }
    }

    // MARK: - 3-beat fill catalog (steps 4-15)

    private static func threeBeatFill(barStart: Int, variation: Int) -> FillData {
        let strip = barStart + 4
        switch variation {

        case 0:  // Tom Descend — hi→mid→floor cascade, snare flourish into crash.
            return FillData(
                stripFrom: strip,
                notes: [
                    MIDIEvent(stepIndex: barStart +  4, note: GMDrum.hiMidTom.rawValue,    velocity: 72,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  5, note: GMDrum.hiMidTom.rawValue,    velocity: 68,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  6, note: GMDrum.hiMidTom.rawValue,    velocity: 78,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  7, note: GMDrum.lowMidTom.rawValue,   velocity: 74,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  8, note: GMDrum.lowMidTom.rawValue,   velocity: 80,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  9, note: GMDrum.lowFloorTom.rawValue, velocity: 76,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 10, note: GMDrum.lowFloorTom.rawValue, velocity: 84,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 11, note: GMDrum.highFloorTom.rawValue,velocity: 82,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 12, note: GMDrum.highFloorTom.rawValue,velocity: 88,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.snare.rawValue,       velocity: 82,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue,       velocity: 93,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,       velocity: 105, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 100)

        case 1:  // Crescendo Roll — 12-step ghost roll building ppp→fff. Bruford / orchestral style.
            return FillData(
                stripFrom: strip,
                notes: (0..<12).map { i in
                    // Exponential velocity curve from 22 to 105
                    let t = Double(i) / 11.0
                    let vel = UInt8(22 + Int(t * t * 83))
                    return MIDIEvent(stepIndex: barStart + 4 + i,
                                     note: GMDrum.snare.rawValue,
                                     velocity: vel, durationSteps: 1)
                },
                addCrash: true, crashVelocity: 100)

        default: // Alternating Toms — hi-mid ↔ floor interplay into snare close. Neil Peart style.
            return FillData(
                stripFrom: strip,
                notes: [
                    MIDIEvent(stepIndex: barStart +  4, note: GMDrum.hiMidTom.rawValue,    velocity: 72,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  5, note: GMDrum.lowFloorTom.rawValue, velocity: 68,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  6, note: GMDrum.hiMidTom.rawValue,    velocity: 78,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  7, note: GMDrum.lowFloorTom.rawValue, velocity: 72,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  8, note: GMDrum.hiMidTom.rawValue,    velocity: 84,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart +  9, note: GMDrum.lowFloorTom.rawValue, velocity: 80,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 10, note: GMDrum.hiMidTom.rawValue,    velocity: 90,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 11, note: GMDrum.lowFloorTom.rawValue, velocity: 86,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 12, note: GMDrum.snare.rawValue,       velocity: 82,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 13, note: GMDrum.snare.rawValue,       velocity: 75,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 14, note: GMDrum.snare.rawValue,       velocity: 92,  durationSteps: 1),
                    MIDIEvent(stepIndex: barStart + 15, note: GMDrum.snare.rawValue,       velocity: 105, durationSteps: 1),
                ],
                addCrash: true, crashVelocity: 100)
        }
    }

    // MARK: - Cymbal run variations

    private static func applyRunVariations(
        to events: [MIDIEvent],
        frame: GlobalMusicalFrame,
        structure: SongStructure,
        fillBars: Set<Int>,
        rng: inout SeededRNG
    ) -> [MIDIEvent] {
        // Count body bars independently of fill bars, then fire a cymbal variation every 8
        // body bars starting at bar 8 (skipping fill bars, which already have varied content).
        // Previously used a run-length fingerprint approach that broke once fills started
        // triggering every 4 bars — the counter never reached 16 so variations never fired.
        var result = events
        var bodyBarCount = 0

        for bar in 0..<frame.totalBars {
            guard let sec = structure.section(atBar: bar),
                  sec.label != .intro && sec.label != .outro else { continue }
            bodyBarCount += 1
            guard !fillBars.contains(bar) else { continue }
            if bodyBarCount >= 8 && bodyBarCount % 8 == 0 {
                let varType = rng.nextInt(upperBound: 3)
                result = applyVariation(to: result, bar: bar, varType: varType)
            }
        }

        return result
    }

    private static func applyVariation(to events: [MIDIEvent], bar: Int, varType: Int) -> [MIDIEvent] {
        let barStart = bar * 16
        switch varType {
        case 0:  // Ride swap: closed hats → ride for one bar
            var ev = events.filter { ev in
                guard ev.stepIndex >= barStart && ev.stepIndex < barStart + 16 else { return true }
                return ev.note != GMDrum.closedHat.rawValue
            }
            for step in Swift.stride(from: 0, to: 16, by: 2) {
                let vel: UInt8 = (step % 8 == 0) ? 78 : 64
                ev.append(MIDIEvent(stepIndex: barStart + step, note: GMDrum.ride.rawValue,
                                    velocity: vel, durationSteps: 1))
            }
            return ev
        case 1:  // Open hat accent on "and of 4" (step 14)
            var ev = events.filter { ev in
                guard ev.stepIndex == barStart + 14 else { return true }
                return ev.note != GMDrum.closedHat.rawValue
            }
            ev.append(MIDIEvent(stepIndex: barStart + 14, note: GMDrum.openHat.rawValue,
                                velocity: 70, durationSteps: 2))
            return ev
        default:  // Crash on beat 1 + open hat on "and of 2" (step 6)
            var ev = events
            if !ev.contains(where: { $0.stepIndex == barStart && $0.note == GMDrum.crash1.rawValue }) {
                ev.append(MIDIEvent(stepIndex: barStart, note: GMDrum.crash1.rawValue,
                                    velocity: 85, durationSteps: 1))
            }
            ev = ev.filter { !($0.stepIndex == barStart + 6 && $0.note == GMDrum.closedHat.rawValue) }
            ev.append(MIDIEvent(stepIndex: barStart + 6, note: GMDrum.openHat.rawValue,
                                velocity: 65, durationSteps: 1))
            return ev
        }
    }
}
